version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    restart: "unless-stopped"
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'YES'
      REDIS_DISABLE_COMMANDS: 'FLUSHDB,FLUSHALL'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  mysql5:
    image: mysql:5.7
    command: --sql-mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    environment:
      MYSQL_DATABASE: 'microservice_sample'
      MYSQL_USER: 'arc9'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'mysql5_data:/var/lib/mysql'
  s3:
    image: minio/minio:latest
    command: server /data
    #    restart: "unless-stopped"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
#      MINIO_BROWSER_REDIRECT_URL: http://localhost:9000
    ports:
      - '9000:9000'
    volumes:
      - 's3_data:/data'
volumes:
  redis_data:
    driver: local
  mysql5_data:
    driver: local
  s3_data:
    driver: local