
CREATE TABLE IF NOT EXISTS USER (
    ID VARCHAR(40) NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(50) UNIQUE,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    GENDER VARCHAR(255) NOT NULL,
    BIO TEXT,
    CREATE_TIME TIMESTAMP(3) NOT NULL,
    LAST_UPDATE_TIME TIMESTAMP(3) NOT NULL
);

