CREATE TABLE IF NOT EXISTS USER (
    ID VARCHAR(40) NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(50) UNIQUE,
    USERNAME VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(256),
    NAME VARCHAR(250) NOT NULL,
    ADDRESS VARCHAR(1000) ,
    VERSION INT NOT NULL DEFAULT 0 ,
    CREATE_TIME TIMESTAMP(3) NOT NULL,
    LAST_UPDATE_TIME TIMESTAMP(3) NOT NULL,
);