name: Docker Image CI

on:
  push:
    branches: [ "main" , "dev", "devops"]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    # - name: Build the Docker image for gateway service
    #   working-directory: ./gateway
    #   run: docker build . --file Dockerfile --tag gateway-service:"$TAG"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Login to JFrog 🐸
      uses: docker/login-action@v1
      with:
        registry: babeswithbothacks.jfrog.io
        username: ${{ secrets.JFROG_USER_WRITER }}
        password: ${{ secrets.JFROG_PASSWORD_WRITER }}
    - name: Build and push 🐳
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./gateway
        push: ${{ github.event_name != 'pull_request' }}
        tags: babeswithbothacks.jfrog.io/docker/gateway-service:0.0.1
