name: Docker Image CI

on:
  push:
    branches: [ "main" , "dev", "devops"]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Build the Docker image for gateway service
      working-directory: ./gateway
      run: docker build . --file Dockerfile --tag gateway-service:$(date +%s)
