name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for gateway service
      run: |
        cd gateway
        docker build . --file Dockerfile --tag gateway-service:$(date +%s)
